# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='nombre')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='vendor')),
                ('image', models.ImageField(upload_to='vendor/', verbose_name='logo')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='vendor', to='cadenas.Vendor', verbose_name='vendor'),
        ),
    ]
