# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 00:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='categoria')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='imagen')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='creado')),
                ('qualification', models.IntegerField(default=0, verbose_name='calificacion')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'verbose_name': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=140, null=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=140, verbose_name='nombre')),
                ('type_uom', models.CharField(choices=[('kilogram', 'Kilogramo'), ('liter', 'Litro'), ('piece', 'Pieza')], default='kilogram', max_length=10, verbose_name='tipo uom')),
                ('conversion', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='conversion')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='productos.Category', verbose_name='categoria')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'verbose_name': 'Product',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='product', to='productos.Product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
