# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20160429_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/categories/YANA-Background.png', upload_to='products/', verbose_name='imagen'),
        ),
    ]
