# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 23:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadenas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_shopping', models.DateField(blank=True, editable=False, null=True, verbose_name='fecha')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', related_query_name='place', to='cadenas.Place', verbose_name='lugar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
    ]
