# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_auto_20160427_1442'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='vendor.Place'),
            preserve_default=False,
        ),
    ]
